
# C:\Users\SMNM\Documents\CompilerPrac2\parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'D5DFD7F8E18BFD4EE68FC9C2E60595B4'
    
_lr_action_items = {'ID':([0,3,9,10,11,12,13,],[1,4,4,4,4,4,4,]),'DIV':([4,5,6,8,15,16,17,18,19,],[-10,-7,10,-9,-6,-5,10,10,-8,]),'$end':([2,4,5,6,7,8,15,16,17,18,19,],[0,-10,-7,-4,-1,-9,-6,-5,-2,-3,-8,]),'OBRACKET':([3,9,10,11,12,13,],[9,9,9,9,9,9,]),'MULT':([4,5,6,8,15,16,17,18,19,],[-10,-7,11,-9,-6,-5,11,11,-8,]),'ADD':([4,5,6,7,8,14,15,16,17,18,19,],[-10,-7,-4,12,-9,12,-6,-5,-2,-3,-8,]),'EQUAL':([1,],[3,]),'CBRACKET':([4,5,6,8,14,15,16,17,18,19,],[-10,-7,-4,-9,19,-6,-5,-2,-3,-8,]),'FLOAT_LITERAL':([3,9,10,11,12,13,],[8,8,8,8,8,8,]),'SUB':([4,5,6,7,8,14,15,16,17,18,19,],[-10,-7,-4,13,-9,13,-6,-5,-2,-3,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([3,9,],[7,14,]),'factor':([3,9,10,11,12,13,],[5,5,15,16,5,5,]),'statement':([0,],[2,]),'term':([3,9,12,13,],[6,6,17,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> ID EQUAL expression','statement',3,'p_statement_expression','parse_ula.py',33),
  ('expression -> expression ADD term','expression',3,'p_expression_add','parse_ula.py',39),
  ('expression -> expression SUB term','expression',3,'p_expression_sub','parse_ula.py',45),
  ('expression -> term','expression',1,'p_expression_term','parse_ula.py',51),
  ('term -> term MULT factor','term',3,'p_term_mult','parse_ula.py',57),
  ('term -> term DIV factor','term',3,'p_term_div','parse_ula.py',63),
  ('term -> factor','term',1,'p_term_factor','parse_ula.py',68),
  ('factor -> OBRACKET expression CBRACKET','factor',3,'p_factor_expression','parse_ula.py',74),
  ('factor -> FLOAT_LITERAL','factor',1,'p_factor_float_literal','parse_ula.py',80),
  ('factor -> ID','factor',1,'p_factor_id','parse_ula.py',86),
]
